trigger:
- master

pool:
  vmImage: 'windows-latest'

strategy:
  matrix:
    Python37:
      python.version: '3.7'
  maxParallel: 1

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UsePythonVersion@0
  inputs: 
    versionSpec: '$(python.version)'
    architecture: 'x64'

- script: pip install robotframework robotframework-pabot robotframework-seleniumlibrary webdrivermanager robotframework-jsonlibrary
  displayName: 'Install dependencies'

- powershell: |
   Write-Host "Robot Framework tests"
   robot --pythonpath . -x outputxunit.xml TestCases.robot.
  displayName: 'Run Robot Framework Tests'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  continueOnError: true
  inputs:
    testResultsFiles: outputxunit.xml